### PR TITLE
General heteropolymer

### PR DESCRIPTION
**Pull request by mrshirts**
## Description
Changes to make it possible to build and run general heteropolymers

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - Make possible build and run with general heteropolymers
  - Changed examples to reflect new builds.

## Questions
- [ ] ???

## Status
- [ ] Maybe more documentation?

### CODE REVIEW

**Comment by cwalker7** [comment]
For the simulation.py example I'm getting a KeyError for 'default_torsion_force_constant' never being assigned.

`Traceback (most recent call last):
  File "simulation.py", line 110, in <module>
    monomer_types=[A],
  File "/projects/chwa2399/software/anaconda/envs/cg_openmm_py37/lib/python3.7/site-packages/foldamers-1.12-py3.7.egg/foldamers/cg_model/cgmodel.py", line 235, in __init__
    self.system = build_system(self, rosetta_functional_form=rosetta_functional_form)
  File "/projects/chwa2399/software/anaconda/envs/cg_openmm_py37/lib/python3.7/site-packages/cg_openmm-1.0-py3.7.egg/cg_openmm/build/cg_build.py", line 816, in build_system
    cgmodel, torsion_force = add_force(cgmodel, force_type="Torsion")
  File "/projects/chwa2399/software/anaconda/envs/cg_openmm_py37/lib/python3.7/site-packages/cg_openmm-1.0-py3.7.egg/cg_openmm/build/cg_build.py", line 693, in add_force
    torsion_force_constant = cgmodel.get_torsion_force_constant(torsion)
  File "/projects/chwa2399/software/anaconda/envs/cg_openmm_py37/lib/python3.7/site-packages/foldamers-1.12-py3.7.egg/foldamers/cg_model/cgmodel.py", line 1176, in get_torsion_force_constant
    return self._get_bonded_parameter(particle_types, "torsion_force_constants")
  File "/projects/chwa2399/software/anaconda/envs/cg_openmm_py37/lib/python3.7/site-packages/foldamers-1.12-py3.7.egg/foldamers/cg_model/cgmodel.py", line 1006, in _get_bonded_parameter
    default_value = forces[default_name]
KeyError: 'default_torsion_force_constant'`

**Comment by mrshirts** [comment]
Fixed for pdb writer (see https://github.com/shirtsgroup/foldamers/pull/37)

**Comment by cwalker7** [comment]
And if I set only bb_bb_bond_force_constant in simulation.py example, instead of a default_bond_force_constant, we also get a KeyError:

`charge not defined for particle type bb using default charge: 0.0 e
charge not defined for particle type sc using default charge: 0.0 e
Warning: No default_bond_force_constant: setting to 1250.0 kJ/(nm**2 mol)
Warning: No default_equil_torsion_angle: setting to 0.0 deg
Warning: No default_torsion_periodicity: setting to 1
Traceback (most recent call last):
  File "simulation.py", line 110, in <module>
    monomer_types=[A],
  File "/projects/chwa2399/software/anaconda/envs/cg_openmm_py37/lib/python3.7/site-packages/foldamers-1.12-py3.7.egg/foldamers/cg_model/cgmodel.py", line 235, in __init__
    self.system = build_system(self, rosetta_functional_form=rosetta_functional_form)
  File "/projects/chwa2399/software/anaconda/envs/cg_openmm_py37/lib/python3.7/site-packages/cg_openmm-1.0-py3.7.egg/cg_openmm/build/cg_build.py", line 798, in build_system
    cgmodel, bond_force = add_force(cgmodel, force_type="Bond")
  File "/projects/chwa2399/software/anaconda/envs/cg_openmm_py37/lib/python3.7/site-packages/cg_openmm-1.0-py3.7.egg/cg_openmm/build/cg_build.py", line 592, in add_force
    bond_force_constant = cgmodel.get_bond_force_constant(bond_indices)
  File "/projects/chwa2399/software/anaconda/envs/cg_openmm_py37/lib/python3.7/site-packages/foldamers-1.12-py3.7.egg/foldamers/cg_model/cgmodel.py", line 1071, in get_bond_force_constant
    return self._get_bonded_parameter(particle_types, "bond_force_constants")
  File "/projects/chwa2399/software/anaconda/envs/cg_openmm_py37/lib/python3.7/site-packages/foldamers-1.12-py3.7.egg/foldamers/cg_model/cgmodel.py", line 1006, in _get_bonded_parameter
    default_value = forces[default_name]
KeyError: 'default_bond_force_constant'
srun: error: shas0606: task 0: Exited with exit code 1`

But it looks like it _is_ initially setting the default_bond_force_constant to the martini value.

**Comment by cwalker7** [comment]
@mrshirts Any thoughts on this bug? I will keep looking as well.

**Comment by mrshirts** [comment]
Ah, I think I missed that error.  Looks like I printed the message that the default was being set, but didn't actually set it.   This should work, but I will do some updates to the cg_openmm code as well after testing (looks like some scripts were not run).

**Comment by mrshirts** [comment]
Actually, I think the cg_openmm ones are running OK now.

**Comment by cwalker7** [comment]
Ah, I see what the problem was, thanks for fixing. The simulation and replica exchange examples are both working now.

**Review by cwalker7 — APPROVED** [review]
Are we good to go on this and the foldamers general heteropolymer update? I think we've sorted out all the issues with the defaults.

**Comment by mrshirts** [comment]
If you are not having any issues, let's go ahead and merge.

**Pull request merged**
