### PR TITLE
Configurational sampling with non-simulated force field parameters

### PR DESCRIPTION
**Pull request by cwalker7**
## Description
Starting point for the force field parameter / sequence optimization scheme in which configurational sampling and MBAR are used to evaluate heat capacity (and other properties of interest) for non-simulated systems.

I set up the basic framework for varying force field parameters using `updateParametersInContext()` function compared to those stored in a cgmodel, and re-evaluating full OpenMM energies for all frames in a replica exchange trajectory set. 

The input format for parameter changes is a dictionary of the form `param_dict['particlename1_particlename2_..._suffix'] = parameter_value`. For example `param_dict['bb_bb_bb_bb_torsion_force_constant'] = new_kt_value` updates the backbone torsion force constant.

I also made a separate heat capacity calculation function since the inputs are different from the case where we are reading energies from a .nc file. 

## Todos
  - [x] Set up input framework for varying different force field parameters
  - [x] Set up input framework for varying sequences
  - [x] Add testing for varying each possible force field parameter
  - [x] Validate results for test cases with full REMD simulation
  - [ ] Set up optimization framework (with SciPy or custom optimization code if necessary) - this should include determining whether a new full simulation is needed.
  - [ ] Set up framework for using trajectory sets from multiple simulations
  - [x] Use basis functions instead of full OpenMM energy evaluations. We can potentially just store the distance matrices of relevant particles instead of full coordinate trajectories when doing the calculation.

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by cwalker7** [comment]
@mrshirts Here is an example energy array that came out of the eval_energies function for changing sigma_sc from 3.5 to 1.0 A, along with the temperature list corresponding to the states used in the REMD simulation. From these you should be able to run the heat capacity part of the example. Also, I had used frame_begin=300,000 and frame_stride=100 when generating the energy array.

[U_array.zip](https://github.com/shirtsgroup/cg_openmm/files/6633035/U_array.zip)

These came from the last 100ns of a 400ns trajectory (optimized temperature spacing) we used in the cg_openmm paper, so just ignore the log space temperatures defined in the example and use the new ones. Specifically, the simulation force field parameters were:

{
  "epsilon_bb": 1.5 kJ/mol,
  "epsilon_sc": 5.0 kJ/mol,
  "sigma_bb": 2.25 A,
  "sigma_sc": 3.5 A,
  "k_bond": 15000 kJ/mol/nm^2,
  "equil_bond_length": 2.44 A,
  "k_angle": 150 kJ/mol/rad^2,
  "equil_bond_angle_bb_bb_bb": 105.5 degrees,
  "k_torsion": 3 kJ/mol,
  "equil_torsion_angle_bb_bb_bb_bb": 16.7 degrees,
  "torsion_periodicity": 1,
  "n_replica": 12,
  "exch_freq": 200,
  "coll_freq": 5 / ps
}

I would say the most likely error is how I reduced the energies. The new heat capacity function I made is essentially taken from the code you wrote originally for the energy arrays read in from the .nc files. Another possibility is an issue with the actual force field parameter updates and energy evaluation - I will look into that more if you think the energy array looks ok.

**Comment by mrshirts** [comment]
What I think is going on here is you are creating the MBAR object with the resampled energies AS IF they were the sampled energies.  What I'm seeing (I may be misunderstand, is passing in the object U_eval, which contains the energies evaluated with a different Hamiltonian (since there were only 12x12xsamples - if it contained old and new energies, then it would be 12 x 24 x samples (or 24x12xsamples, depends how you organized it), then passed in to initialize the MBAR object.  So then it assumes that the energies you measured were the energies that lead to the given observations. 

But you want to initialize the MBAR object with the energies that were actually generated, to find the original probabilities of each sample, then use the computeMultipleExpectations functions to calculate expectations of energies at the reevaluated energies.

Let me know if I misunderstood the code!

**Comment by mrshirts** [comment]
You should be able to run it from computeExpectations as well, as long as the array that is passed in has both the new states and the reevaluated states.  Then you will get ntemp*(1+number_reevaluted states) heat capacities out, just have to keep track of the bookkeeping.  You can probably use the same code as before, as long as the u_eval is properly num_temps*(1+num_reevaluated_hamiltonians)*(nsamples_per_state) long, and N_k = n_temps*[nsamples_per_state] + num_temps*num_reevaluated+hamiltonians*[0] (i.e. zeros for the number of states that are not evaluated).  That way, it will have all the information necessary for the MBAR solutions on JUST the sampled states, and the reevaluated states.

N_effective samples should be of size num_temps*(1+num_reevaluated_hamiltonians), and you want to see for which Hamiltonians it starts to drop lower.

If you use trajectories run with multiple hamiltonians to reweight from, then their N_k's will be nonzero.

**Comment by cwalker7** [comment]
> What I think is going on here is you are creating the MBAR object with the resampled energies AS IF they were the sampled energies.

Yeah you are right, I see the problem now. I'll start working on fixing this.

**Comment by cwalker7** [comment]
Everything seems to be working correctly with the reweighting / energy evaluation here and the new multiple folded state update. The reevaluated energies are as expected now, and match the original reference data when no force field parameters are changed. Issues with seg faults in the tests are also resolved here. I'll merge this huge PR now and document remaining tasks as issues since it's getting hard to keep track of all the changes.

**Pull request merged**
