### PR TITLE
free energy code for conformational state changes

### PR DESCRIPTION
**Pull request by cwalker7**
## Description
New function and example for calculating free energy difference between conformational states (folded vs. unfolded or any amount of other states) as a function of temperature. For now the states are generated randomly in the example.

## Todos
Add methods for determining the conformational state associated with each frame and energy:
  - [x] By native contact fraction (i.e., similarity to folded state)
  - [ ] By clustering based on RMSD

## Status
- Working on adding the state classification methods

### CODE REVIEW

**Comment by cwalker7** [comment]
For randomly assigned states to the output in the native contacts examples folder, we get a plot like this:
[free_energy2.pdf](https://github.com/shirtsgroup/cg_openmm/files/5058570/free_energy2.pdf)

**Comment by cwalker7** [comment]
**More updates:**

Updated the plotting functions for replica exchange output.
- The replica energies as a function of simulation time is now replaced with state energies as a function of time (legend with temps should have been states in old version)
- Added plot for energy histogram / overlap of states
- Use subplots to split up data if we have a lot of replicas (not really much better - needs to be separate full page plots I'm thinking)

Added function for writing pdb trajectories by state, rather than by replica. Could also run the rmsd clustering in analyze_foldamers on these, using 1 cluster, to produce the most representative structure (medoid) for each temp.

**Comment by mrshirts** [comment]
Can you maybe post examples of plots in the PR?

**Comment by cwalker7** [comment]
Yeah, I just want to try to fix some of the plot formatting first.

**Comment by mrshirts** [comment]
> Yeah, I just want to try to fix some of the plot formatting first.

makes sense.

**Comment by cwalker7** [comment]
Ok I think I've finally got the multi-page pdf plots working. I have it plotting 6 replicas per page as the default, but maybe even less would be better.

**Comment by cwalker7** [comment]
[rep_ex_ener.pdf](https://github.com/shirtsgroup/cg_openmm/files/5091761/rep_ex_ener.pdf)
[rep_ex_ener_hist.pdf](https://github.com/shirtsgroup/cg_openmm/files/5091763/rep_ex_ener_hist.pdf)
[rep_ex_states.pdf](https://github.com/shirtsgroup/cg_openmm/files/5091764/rep_ex_states.pdf)

Here are some example plots for 36 replicas.

**Comment by cwalker7** [comment]
Figured out why the state pdb trajectories were so weird in VMD - I hadn't assigned units to the positions for each state (which we store as nanometers), and VMD assumed the units were Angstrom.  For the replica pdbs, we were giving the nanometer units to the mdtraj PDB trajectory writer, and it is apparently converting them there to Angstrom.

I also centered the state pdb trajectories so they are not switching back and forth in space. Might need to be updated if we are using multiple different particle masses.

**Comment by cwalker7** [comment]
Still working on the example script for the native contacts / free energy, but I've updated the native contacts calculation to use mdtraj to compute the relevant distances for an entire trajectory in one go. I estimate the speedup is about 300x. It takes about 3 minutes to analyze 180,000 frames.

**Comment by mrshirts** [comment]
> Still working on the example script for the native contacts / free energy, but I've updated the native contacts calculation to use mdtraj to compute the relevant distances for an entire trajectory in one go. I estimate the speedup is about 300x. It takes about 3 minutes to analyze 180,000 frames.

300x is nothing to sneeze at!

**Comment by cwalker7** [comment]
This should provide a fix for #66 , by stripping the units off the positions, and adding them back after the distance calculation. We may want to look into why the numpy math on the positions in the random builder example causes the units to get lost.

**Comment by cwalker7** [comment]
Added a native contacts test.

Pytest interpreted test_forces and test_force in cg_build as functions it should test, whenever we import cg_build, so I just renamed those to check_force and check_forces to avoid needing extra pytest commands to ignore them.

**Comment by cwalker7** [comment]
A lot of important updates here which we've already tested and reviewed in PR #70, so I'll merge. One thing we should verify is the uncertainty in the free energy calculation (such as by comparing with bootstrapping uncertainty) - I'll make it a separate issue.

Also note that we have now switched the replica exchange scheme from 'swap-all' to 'swap-neighbors' due to possible unresolved bug with the former.

**Pull request merged**
